namespace BA_MobileGPS.Utilities
{
    public enum MobileResourceNames
    {
        #region Common
        Common_Label_BAGPS,
        Common_NoInternet,
        Common_Lable_All,
        Common_Lable_More,
        Common_Lable_NotFound,
        Common_Lable_ChooseCompany,
        Common_Loading_Processing1,
        Common_Lable_ChooseVehicleGroup,
        Common_Message_Loading,
        Common_Label_Notification,
        Common_Message_Warning,
        Common_Message_Skip,
        Common_Message_NotPermission,
        Common_Label_HighLight,
        Common_Label_Features,
        Common_Label_Report,
        Common_Button_OK,
        Common_Button_Send,
        Common_Button_Save,
        Common_Button_View,
        Common_Button_Cancel,
        Common_Button_Yes,
        Common_Button_No,
        Common_Button_Close,
        Common_Message_ErrorTryAgain,
        Common_Message_SearchText,
        Common_Message_SearchTextValid,
        Common_Label_CameraTitle,
        Common_Label_Year,
        Common_Label_Month,
        Common_Label_Day,
        Common_Label_DayUpper,
        Common_Label_Days,
        Common_Label_Day2,
        Common_Label_Hour,
        Common_Label_Hours,
        Common_Label_Hour2,
        Common_Label_Minute,
        Common_Label_Minutes,
        Common_Label_Minute2,
        Common_Label_Second,
        Common_Label_Duration,
        Common_Label_Duration2,
        Common_Message_CameraUnavailable,
        Common_Message_CameraUnsupported,
        Common_Message_PickPhotoUnsupported,
        Common_Message_PickPhotoPermissionNotGranted,
        Common_Message_ViewAvatar,
        Common_Message_TakeNewPhoto,
        Common_Message_ChooseAvailablePhotos,
        Common_Button_Update,
        Common_Message_RequiredDateTimeOver,
        Common_Message_RequiredVehicle,
        Common_Button_Update_Later,
        Common_Value_SelectGender,
        Common_Value_SelectReligion,
        Common_Lable_Car,
        Common_Label_Vehicle,
        Common_Lable_KmUnit,
        Common_Lable_NMUnit,
        Common_Property_Invalid,
        Common_Property_NullOrEmpty,
        Common_Property_MinLength,
        Common_Property_DangerousChars,
        Common_Property_NotContainChars,
        Common_Property_DangerousCharShow,
        Common_Message_RequiredNullOrEmpty,
        Common_Label_TitleGrid_VehiclePlate,
        Common_Label_TitleGrid_OrderNumber,
        Common_Label_Time,
        Common_Label_Close,
        Common_Label_Open,
        Common_Label_TurnOn,
        Common_Label_TurnOff,
        Common_Label_Craning,
        Common_Label_Normal,
        Common_Label_Lowerben,
        Common_Label_LoweredBen,
        Common_Message_SelectCompany,
        Common_Message_NotFindYourCar,
        Common_Message_LoadMore,
        Common_Label_DoorClose,
        Common_Label_DoorOpen,
        #endregion Common

        #region Login
        Login_Textbox_UserName,
        Login_Textbox_Password,
        Login_Button_Login,
        Login_Checkbox_Rememberme,
        Login_Checkbox_Autologin,
        Login_Lable_Forgotpassword,
        Login_Lable_RegisterSales,
        Login_Lable_ExperienceBA,
        Login_Lable_Hotline,
        Login_Lable_SelectLanguage,
        Login_Message_AccountPasswordIncorrect,
        Login_Message_AccountAllowedSystem,
        Login_Message_AccountLocked,
        Login_Message_LoginWebOnly,
        Login_Message_UpdateVersionNew,
        Login_Message_UpdateVersionMessage,
        Login_ForgotPassword_PopupTitle,
        Login_ForgotPassword_PopupContent,
        Login_Popup_Starting_Page,
        Login_Popup_Manual,
        Login_Popup_Guarantee,
        Login_Popup_RegisterSupport,
        Login_Popup_Network,
        Login_Popup_BAGPSExperience,
        Login_UserNameProperty_NullOrEmpty,
        Login_PasswordProperty_NullOrEmpty,
        #endregion Login

        #region ChangePassword
        ChangePassword_Label_Title,
        ChangePassword_Label_OldPassword,
        ChangePassword_Label_OldPassword1,
        ChangePassword_Label_NewPassword,
        ChangePassword_Label_NewPassword1,
        ChangePassword_Label_NewPasswordConfirm,
        ChangePassword_Label_NewPasswordConfirm1,
        ChangePassword_Validate_OldPasswordEmpty,
        ChangePassword_Validate_NewPasswordEmpty,
        ChangePassword_Validate_NewPasswordMinLenght,
        ChangePassword_Validate_NewPasswordConfirmInvalid,
        ChangePassword_Validate_OldPasswordInvalid,
        ChangePassword_Validate_NewPasswordIsSameOldPassword,
        ChangePassword_Validate_NewPasswordIsSameUserName,
        ChangePassword_Button_ChangePassword,
        ChangePassword_Message_UpdateSuccess,
        #endregion ChangePassword

        #region UserInfo
        UserInfo_Label_Title,
        UserInfo_Label_LoyaltyCustomer,
        UserInfo_Label_Intro,
        UserInfo_Label_FullName,
        UserInfo_Label_Choose_Birthday,
        UserInfo_Label_FullName_MinLengthError,
        UserInfo_Label_PhoneNumber,
        UserInfo_Label_Email,
        UserInfo_Label_DayOfBirth,
        UserInfo_Label_Gender,
        UserInfo_Label_Career,
        UserInfo_Label_Role,
        UserInfo_Label_Religion,
        UserInfo_Label_Address,
        UserInfo_Label_Facebook,
        #endregion UserInfo

        #region RegisterConsult
        RegisterConsult_Label_TilePage,
        RegisterConsult_Label_DescriptionFirstPage,
        RegisterConsult_Label_UserName,
        RegisterConsult_Label_Phone,
        RegisterConsult_Label_TransportType,
        RegisterConsult_Label_Provinces,
        RegisterConsult_Label_Content,
        RegisterConsult_Button_Register,
        RegisterConsult_Message_Validate_IsNull_UserName,
        RegisterConsult_Message_Validate_IsNull_Phone,
        RegisterConsult_Message_Validate_MaxLength_UserName,
        RegisterConsult_Message_Validate_Rule_Phone,
        RegisterConsult_Message_Validate_Rule_Double_Phone,
        RegisterConsult_Message_Validate_IsNull_CountryCode,
        RegisterConsult_Message_ErrorRegister,
        RegisterConsult_Message_ErrorExistsPhone,
        RegisterConsult_Message_SuccessRegister,
        RegisterConsult_Label_TitlePopup,
        RegisterConsult_Button_ClosePopup,
        #endregion RegisterConsult

        #region Feedback
        Feedback_Label_TilePage,
        Feedback_Label_SubTilePage,
        Feedback_Label_Content,
        Feedback_Button_Send,
        Feedback_Message_SendSuccess,
        Feedback_Message_SendFail,
        Feedback_Message_MarkRequired,
        Feedback_Message_OverMax,
        Feedback_Message_FilterWord,
        Feedback_Message_Guider1,
        Feedback_Message_Guider2,
        Feedback_Label_Thanks,
        Feedback_Notice_NoEntry,
        Feedback_Notice_SendSuccess,
        Feedback_Notice_SendFail,
        #endregion Feedback

        #region Menu
        Menu_Label_Favorite,
        Menu_Label_SettingFavorite,
        Menu_TabItem_Home,
        Menu_TabItem_Vehicle,
        Menu_TabItem_Monitoring,
        Menu_TabItem_Voyage,
        Menu_TabItem_Route,
        Menu_TabItem_Account,
        Home_Label_Highlight,
        Home_Label_Features,

        #endregion Menu

        #region favorites
        Favorites_Label_TilePage,
        Favorites_Message_SaveSuccess,
        Favorites_Message_SaveFail,
        Favorites_Message_RequiredOne,

        #endregion favorites

        #region ForgotPassword

        // Forgot Password Page
        ForgotPassword_Label_TilePage,

        ForgotPassword_Label_AccountName,
        ForgotPassword_Label_Phone,
        ForgotPassword_Label_Notes,
        ForgotPassword_Button_SendInfor,
        ForgotPassword_Message_Validate_IsNull_AccountName,
        ForgotPassword_Message_Validate_MaxLength_AccountName,
        ForgotPassword_Message_Validate_ConstantHTML_AccountName,
        ForgotPassword_Message_Validate_IsNull_Phone,
        ForgotPassword_Message_Validate_Rule_Phone,
        ForgotPassword_Message_ErrorSendSMS,
        ForgotPassword_Message_ErrorCheckInforUser,
        ForgotPassword_Message_ErrorOverCountOneDay,
        ForgotPassword_Message_ErrorWasRegisterSuccess,
        ForgotPassword_Message_ErrorErrorSendSMS,
        ForgotPassword_Message_ErrorErrorLogSMS,
        ForgotPassword_Message_SuccessSendSMS,

        // verify code
        VerifyCodeMS_Label_TilePage,

        VerifyCodeMS_Label_Code,
        VerifyCodeMS_Label_TimeCountDown,
        VerifyCodeMS_Button_CheckVerify,
        VerifyCodeMS_Button_ResendCode,
        VerifyCodeMS_Message_Validate_IsNull_Code,
        VerifyCodeMS_Message_Validate_MaxLength_Code,
        VerifyCodeMS_Message_ErrorVerifyCode,
        VerifyCodeMS_Message_ErrorWrongVerifyCode,
        VerifyCodeMS_Message_ErrorTimeOut,
        VerifyCodeMS_Message_ErrorOverWrongPerCode,
        VerifyCodeMS_Message_ErrorOverWrongPerDay,

        // Changepass
        ChangePassForgot_Label_TilePage,

        ChangePassForgot_Label_NewPassword,
        ChangePassForgot_Label_ReplyPassword,
        ChangePassForgot_Button_ChangePass,
        ChangePassForgot_Message_Validate_IsNull_NewPassword,
        ChangePassForgot_Message_Validate_MaxLength_NewPassword,
        ChangePassForgot_Message_Validate_MinLength_NewPassword,
        ChangePassForgot_Message_Validate_IsNull_ReplyPassword,
        ChangePassForgot_Message_Validate_Equal_ReplyPassword,
        ChangePassForgot_Message_ErrorChangePassword,
        ChangePassForgot_Label_TitlePopupSuccessChangePassword,
        ChangePassForgot_Message_SuccessChangePassword,
        ChangePassForgot_Button_ClosePopup,
        #endregion ForgotPassword

        #region ListVehicle
        ListVehicle_Label_Title,
        ListVehicle_Label_Title2,
        ListVehicle_Label_Search,
        ListVehicle_Label_NotFound,
        VehicleLookUp_Label_Title,
        ListVehicle_Label_NotFoundVehicleGroup,
        ListVehicle_Label_ChooseVehicleGroup,
        ListVehicle_Label_ChooseCompany,
        ListVehicle_Label_FilterData,
        ListVehicle_Label_Vehicle_Expired,
        ListVehicle_Label_Vehicle_Unpaid,
        ListVehicle_Label_Vehicle_Stop_Service,
        ListVehicle_Label_Vehicle_Expiration_Date,
        ListVehicle_Label_Vehicle_Expired_Date,
        ListVehicle_Label_Vehicle_Stop_Date,
        ListVehicle_Label_Vehicle_Own_Fee,
        ListVehicle_Label_SelectCommand,
        ListVehicle_Label_SortBy,
        ListVehicle_Label_ByVehicle,
        ListVehicle_Label_ByVehiclePlate,
        ListVehicle_Label_ByTime,
        ListVehicle_Label_ByState,
        ListVehicle_Label_Default,
        ListVehicle_Label_VehicleNormal,
        ListVehicle_Label_VehicleNormal2,
        ListVehicle_Label_VehicleNormal2VMS,
        ListVehicle_Label_VehicleStop,
        ListVehicle_Label_VehicleStop2,
        ListVehicle_Label_VehicleStop2VMS,
        ListVehicle_Label_VehicleSpeeding,
        ListVehicle_Label_VehicleSpeeding2,
        ListVehicle_Label_VehicleSpeeding2VMS,
        ListVehicle_Label_VehicleLostGPS,
        ListVehicle_Label_VehicleLostGPS2,
        ListVehicle_Label_VehicleLostGPS2VMS,
        ListVehicle_Label_VehicleLostGSM,
        ListVehicle_Label_VehicleLostGSM2,
        ListVehicle_Label_VehicleLostGSM2VMS,
        ListVehicle_Label_Note,
        CompanyLookUp_Label_Title,
        CompanyLookUp_Label_NotFound,
        CompanyLookUp_Label_Search,
        #endregion ListVehicle

        #region Online
        Online_Label_TitlePage,
        Online_Label_Determining,
        Online_Label_SeachVehicle,
        Online_Label_SeachVehicle2,
        Online_Label_SeachVehicle3,
        Online_Label_StatusCarAll,
        Online_Label_StatusCarDebtMoney,
        Online_Label_StatusCarMoving,
        Online_Label_StatusCarStoping,
        Online_Label_StatusCarEngineOff,
        Online_Label_StatusCarEngineOn,
        Online_Label_StatusCarStopOn,
        Online_Label_StatusCarOverVelocity,
        Online_Label_StatusCarLostGPS,
        Online_Label_StatusCarLostGSM,
        Online_Label_StatusCarSatelliteError,
        Online_Label_TotalCar,
        Online_Label_TotalVehicle,
        Online_Button_Detail,
        Online_Button_Router,
        Online_Button_ShowHideBorder,
        Online_Button_ShowBorder,
        Online_Button_HideBorder,
        Online_Label_VehicleInfo,
        Online_Label_Last,
        Online_Label_AtTime,
        Online_Label_TotalKm,
        Online_Label_Velocity,
        Online_Label_Engine,
        Online_Label_AirConditioning,
        Online_Label_Cardoor,
        Online_Label_Location,
        Online_Message_CarDebtMoney,
        Online_Message_CarStopService,
        Online_Message_CarStopServiceFrom,
        Online_Action_UpdateAdminUserSetting,
        Online_Lable_UpdateAdminUserSetting,
        Online_Lable_SetupBoundary,
        Online_Button_Option,
        Online_CheckBox_Distance,

        #endregion Online

        #region Route
        Route_Label_Title,
        Route_Label_ListTitle,
        Route_Label_Time,
        Route_Label_Vgps,
        Route_Label_Status,
        Route_Label_SearchVehicle,
        Route_Label_SearchFishing,
        Route_Label_VehicleEmpty,
        Route_Label_RouteNotFound,
        Route_Label_RouteNotFoundVMS,
        Route_Label_RouteNotExist,
        Route_Label_RouteNotExistVMS,
        Route_Label_More,
        Route_Label_Coordinates,
        Route_Label_Move,
        Route_Label_StopParking,
        Route_Label_LostSignal,
        Route_Label_StartDateMustSmallerThanEndDate,
        Route_Label_TotalTimeLimit,
        Route_Label_EndDateLimit,
        Route_Label_AccountIsExpired,
        Route_Label_FromDateToDateLimit,
        Route_Label_ToDateFromDateLimit,
        Route_Label_FromDateLimit,
        Route_Label_ToDateLimit,
        Route_Label_OverDateLimit,
        Route_Label_DistanceTitle,
        Route_Label_FeeVMS,
        Route_Label_Circle,
        #endregion Route

        #region Alert Online

        Alert_Label_TilePage,
        Alert_Label_TileHandlePage,
        Alert_Label_NotFound,
        Alert_Label_Handler,
        Alert_Label_Time,
        Alert_Label_AlertType,
        Alert_Label_SearchVehicle,
        Alert_Label_AlertProcessed,
        Alert_Label_AlertRead,
        Alert_Label_AlertHandling,
        Alert_Label_AlertDetail,
        Alert_Message_RequiredContent,
        Alert_Message_RequireHandleMinLenght,
        Alert_Message_Alert_Success,
        Alert_Message_Alert_Fail,
        Alert_Message_AlertLongStop,
        Alert_Message_AlertLostGPS,
        Alert_Message_AlertLostGSM,

        #endregion Alert Online

        #region VehicleDebtMoney
        VehicleDebtMoney_Label_TilePage,
        VehicleDebtMoney_Label_SearchFee,
        VehicleDebtMoney_Label_VehicleDebt,
        VehicleDebtMoney_Label_Header1,
        VehicleDebtMoney_Label_Header2,
        VehicleDebtMoney_Label_ContactFee,
        VehicleDebtMoney_Label_PlaceholderSearchKey,
        VehicleDebtMoney_Label_TotalVehicle,
        VehicleDebtMoney_Label_TitleGrid_ExpireDate,
        VehicleDebtMoney_Label_TitleGrid_RenewedDate,
        VehicleDebtMoney_Label_TitleGrid_CountExpireDate,
        VehicleDebtMoney_Label_TitleGrid_Descriptions,
        VehicleDebtMoney_Label_Error_SearchCommand,
        VehicleDebtMoney_Label_NoValue_SearchCommand,
        VehicleDebtMoney_Message_ID2,
        VehicleDebtMoney_Message_ID3,
        VehicleDebtMoney_Message_ID128,
        VehicleDebtMoney_Message_ID0,
        VehicleDebtMoney_Message_ID1,
        VehicleDebtMoneyMessage_SuccessRegister,
        VehicleDebtMoney_Label_TitlePopup,
        VehicleDebtMoney_Button_ClosePopup,
        VehicleDebtMoney_TitleStatus,
        VehicleDebtMoney_Contact,
        #endregion VehicleDebtMoney

        #region vehicledetail
        DetailVehicle_Label_TilePage,
        DetailVehicleVMS_Label_TilePage,
        DetailVehicle_Label_InforFee,
        DetailVehicle_MessageFee,
        DetailVehicle_Label_TileInforVehicle,
        DetailVehicle_Label_VehiclePlate,
        DetailVehicle_Label_Address,
        DetailVehicle_Label_Coordinates,
        DetailVehicle_Label_Time,
        DetailVehicle_Label_Speed,
        DetailVehicle_Label_Engineer,
        DetailVehicle_Label_KilometInToDay,
        DetailVehicle_Label_KilometInMonth,
        DetailVehicle_Label_KilometAccumulated,
        DetailVehicle_Label_CountStopVehicle,
        DetailVehicle_Label_ParkingVehicleNow,
        DetailVehicle_Label_ParkingTurnOnVehecle,
        DetailVehicle_Label_AirCondition,
        DetailVehicle_Label_CountOpenDoor,
        DetailVehicle_Label_Crane,
        DetailVehicle_Label_Ben,
        DetailVehicle_Label_Ben_Crane,
        DetailVehicle_Label_Door,
        DetailVehicle_Label_Temperature,
        DetailVehicle_Label_Fuel,
        DetailVehicle_Label_Concrete,
        DetailVehicle_Label_MemoryStick,
        DetailVehicle_Label_SpeedOverCount,
        DetailVehicle_Label_MinutesOfDrivingTimeContinuous,
        DetailVehicle_Label_MinutesOfDrivingTimeInDay,
        DetailVehicle_Label_InforBGT,
        DetailVehicle_Label_InforSIM,
        DetailVehicle_Label_DriverName,
        DetailVehicle_Label_DriverLicense,
        DetailVehicle_Label_DriverPhone,
        DetailVehicle_Label_DepartmentOfManagement,
        DetailVehicle_Label_ValueMemoryStick_Normal,
        DetailVehicle_Label_ValueMemoryStick_NotInit,
        DetailVehicle_Label_ValueMemoryStick_Lost,
        DetailVehicle_Label_ValueConcrete_Normal,
        DetailVehicle_Label_ValueConcrete_Mixer,
        DetailVehicle_Label_ValueConcrete_Concreting,
        DetailVehicle_Label_SimPhoneNumber,
        DetailVehicle_Label_JoinSystemDate,
        DetailVehicle_Label_Vehicle_Expiration_Date,
        DetailVehicle_Label_Vehicle_Sim_Surplus,
        DetailVehicle_Label_Vehicle_Status_Current,
        DetailVehicle_Label_ExpirationDate,
        DetailVehicle_Label_Status,
        DetailVehicle_Label_Packageinformation,
        DetailVehicle_Label_PackageName,
        DetailVehicle_Label_Provider,
        DetailVehicle_Label_Packagecapacity,
        DetailVehicle_Label_DaysOfStorage,
        DetailVehicle_Label_ChannelOfStorage,
        DetailVehicle_Label_Positioning,
        DetailVehicle_Label_Photo,
        DetailVehicle_Label_Video,
        DetailVehicle_Label_DeviceInformation,
        DetailVehicle_Label_ChannelHasCamera,
        DetailVehicle_Label_ActiveChannel,
        DetailVehicle_Label_DriveCapacity,
        DetailVehicle_Label_Network,
        #endregion vehicledetail

        #region datetimepicker
        Common_Label_TimePicker,
        Common_Label_DatePicker,
        #endregion datetimepicker

        #region report
        Common_Combobox_TitleCompany,
        Common_Combobox_TitleVehicle,
        Common_Button_Search,
        Common_Button_ExportExcell,
        Common_Button_Loadmore,
        Common_Button_SaveShowHideColumn,
        Common_Label_CompanyReport,
        Common_Label_PlaceHolder_CompanyReport,
        Common_Label_PlaceHolder_SearchKey,
        Common_Label_PlaceHolder_FromDate,
        Common_Label_PlaceHolder_ToDate,
        Common_Label_Grid_STT,
        Common_Label_Grid_VehiclePlate,
        Common_Label_Grid_FromDate,
        Common_Label_Grid_ToDate,
        Common_Message_ErrorSearch,
        Common_Message_ErrorExportExcell,
        Common_Message_SuccessExportExcell,
        Common_Message_ErrorFromDateBiggerToDate,
        Common_Message_ErrorIsNotRuleFromDate,
        Common_Message_ErrorIsNotRuleToDate,
        Common_Message_ErrorIsNullFromDate,
        Common_Message_ErrorIsNullToDate,
        Common_Message_NoSelectVehiclePlate,
        Common_Message_PleaseSelectVehicle,
        Common_Message_NoData,
        Common_Message_NoDataJoinDay,
        Common_Message_ErrorOverDateSearch,
        Common_Label_TitleShowHideColumn,
        Common_Label_All,

        PourFuelReport_Label_TitlePage,
        PourFuelReport_Label_TitleDetailPage,
        PourFuelReport_Label_StatusPourFuel,
        PourFuelReport_Label_PlaceHolder_Liters,
        PourFuelReport_Label_CheckBox_Number,
        PourFuelReport_Label_CheckBox_Liters,
        PourFuelReport_Label_CheckBox_Date,
        PourFuelReport_Label_CheckBox_Address,
        PourFuelReport_Label_CheckBox_Status,

        PourFuelReport_ComboBox_Status_Pour,
        PourFuelReport_ComboBox_Status_Absorb,
        PourFuelReport_ComboBox_Status_SuspiciousPour,
        PourFuelReport_ComboBox_Status_SuspiciousAbsorb,

        PourFuelReport_Table_Serial,
        PourFuelReport_Table_Date,
        PourFuelReport_Table_Status,
        PourFuelReport_Table_Address,
        PourFuelReport_Table_Liters,

        PourFuelReport_Message_ValidateError_Liters,

        PourFuelReport_Status_ValidateError_Pour,
        PourFuelReport_Status_ValidateError_Absorb,
        PourFuelReport_Status_ValidateError_SuspiciousPour,
        PourFuelReport_Status_ValidateError_SuspiciousAbsorb,

        PourFuelReport_Label_Detail_Status,
        PourFuelReport_Label_Detail_Liters,
        PourFuelReport_Label_Detail_Date,
        PourFuelReport_Label_Detail_Address,
        PourFuelReport_Detail_Label_Liters,

        PourFuelReport_Label_TitleChartDetailPage,

        ChartFuelReport_Y_Liters,
        ChartFuelReport_Tank,
        ChartFuelReport_Total,
        ChartFuelReport_X_Date,
        ChartFuelReport_ShowByTime,

        Helper_Label_PourFuel,

        FuelsSummariesReport_Label_TilePage,
        FuelsSummariesReportTotal_Label_TilePage,
        FuelsSummariesReport_Label_TitlePageDetail,
        FuelsSummariesReport_Label_DetailVehiclePlate,
        FuelsSummariesReport_Label_Date,
        FuelsSummariesReport_Label_StartTime,
        FuelsSummariesReport_Label_EndTime,
        FuelsSummariesReport_Label_StartTime2,
        FuelsSummariesReport_Label_EndTime2,
        FuelsSummariesReport_Label_NumberOfPour,
        FuelsSummariesReport_Label_NumberOfSuction,
        FuelsSummariesReport_Label_FirtLits,
        FuelsSummariesReport_Label_LitersOfPour,
        FuelsSummariesReport_Label_LitersOfSuction,
        FuelsSummariesReport_Label_LastLits,
        FuelsSummariesReport_Label_LitsConsumable,
        FuelsSummariesReport_Label_MinutesOfManchineOn,
        FuelsSummariesReport_Label_MinuteOfMachineOnStop,
        FuelsSummariesReport_Label_TotalKmGps,
        FuelsSummariesReport_Label_QuotaRegulations,
        FuelsSummariesReport_Label_QuotaReality,
        FuelsSummariesReport_Label_PopupStart,
        FuelsSummariesReportTotal_Label_PopupStart,
        FuelsSummariesReport_Label_PopupEnd,
        FuelsSummariesReportTotal_Label_PopupEnd,
        FuelsSummariesReport_Label_PopupLastLits,
        FuelsSummariesReportTotal_Label_PopupLastLits,
        FuelsSummariesReport_Label_PopupLitsConsumable,
        FuelsSummariesReportTotal_Label_PopupLitsConsumable,

        FuelsSummariesReport_Table_Serial,
        FuelsSummariesReport_Table_Date,
        FuelsSummariesReport_Table_StartEndTime,
        FuelsSummariesReport_Table_StartEndTime2,
        FuelsSummariesReport_Table_NumberOfPour,
        FuelsSummariesReport_Table_NumberOfSuction,
        FuelsSummariesReport_Table_FirtLits,
        FuelsSummariesReport_Table_LitersOfPour,
        FuelsSummariesReport_Table_LitersOfSuction,
        FuelsSummariesReport_Table_LastLits,
        FuelsSummariesReport_Table_LitsConsumable,
        FuelsSummariesReport_Table_TotalKmGps,
        FuelsSummariesReport_Table_MinutesOfManchineOn,
        FuelsSummariesReport_Table_MinuteOfMachineOnStop,
        FuelsSummariesReport_Table_QuotaRegulations,
        FuelsSummariesReport_Table_QuotaReality,

        FuelsSummariesReport_CheckBox_Serial,
        FuelsSummariesReport_CheckBox_Date,
        FuelsSummariesReport_CheckBox_StartEndTime,
        FuelsSummariesReport_CheckBox_NumberOfPour,
        FuelsSummariesReport_CheckBox_NumberOfSuction,
        FuelsSummariesReport_CheckBox_FirtLits,
        FuelsSummariesReport_CheckBox_LitersOfPour,
        FuelsSummariesReport_CheckBox_LitersOfSuction,
        FuelsSummariesReport_CheckBox_LastLits,
        FuelsSummariesReport_CheckBox_LitsConsumable,
        FuelsSummariesReport_CheckBox_TotalKmGps,
        FuelsSummariesReport_CheckBox_MinutesOfManchineOn,
        FuelsSummariesReport_CheckBox_MinuteOfMachineOnStop,
        FuelsSummariesReport_CheckBox_QuotaRegulations,
        FuelsSummariesReport_CheckBox_QuotaReality,

        ActivitySummariesReport_Label_TilePage,
        ActivitySummariesReport_Label_TitlePageDetail,
        ActivitySummariesReport_Label_TitleJoinNameDate,
        ActivitySummariesReport_Label_JoinDay,
        ActivitySummariesReport_Label_VehicleType,
        ActivitySummariesReport_Label_VehiclePlate,
        ActivitySummariesReport_Label_CurrentTime,
        ActivitySummariesReport_Label_StartTime,
        ActivitySummariesReport_Label_EndTime,
        ActivitySummariesReport_Label_ActiveTime,
        ActivitySummariesReport_Label_StopParkingTime,
        ActivitySummariesReport_Label_KmGPS,
        ActivitySummariesReport_Label_KmCO,
        ActivitySummariesReport_Label_NumberOfStopParking,
        ActivitySummariesReport_Label_MinutesTurnOnAirConditioner,
        ActivitySummariesReport_Label_Vmax,
        ActivitySummariesReport_Label_Vmedium,

        ActivitySummariesReport_Table_Serial,
        ActivitySummariesReport_Table_CurrentTime,
        ActivitySummariesReport_Table_StartEndTime,
        ActivitySummariesReport_Table_ActiveTime,
        ActivitySummariesReport_Table_StopParkingTime,
        ActivitySummariesReport_Table_KmGPS,
        ActivitySummariesReport_Table_KmCO,
        ActivitySummariesReport_Table_VehicleType,
        ActivitySummariesReport_Table_VehiclePlate,
        ActivitySummariesReport_Table_NumberOfStopParking,
        ActivitySummariesReport_Table_MinutesTurnOnAirConditioner,
        ActivitySummariesReport_Table_Vmax,
        ActivitySummariesReport_Table_Vmedium,

        ActivitySummariesReport_CheckBox_VehicleType,
        ActivitySummariesReport_CheckBox_VehiclePlate,
        ActivitySummariesReport_CheckBox_Vmax,
        ActivitySummariesReport_CheckBox_CurrentTime,
        ActivitySummariesReport_CheckBox_ActiveTime,
        ActivitySummariesReport_CheckBox_StopParkingTime,
        ActivitySummariesReport_CheckBox_KmGPS,
        ActivitySummariesReport_CheckBox_KmCO,
        ActivitySummariesReport_CheckBox_NumberOfStopParking,
        ActivitySummariesReport_CheckBox_MinutesTurnOnAirConditioner,
        ActivitySummariesReport_CheckBox_Vmedium,

        DetailsReport_Label_TilePage,
        DetailsReport_Label_TitlePageDetail,
        DetailsReport_Label_VehicleType,
        DetailsReport_Label_VehiclePlate,
        DetailsReport_Label_CurrentTime,
        DetailsReport_Label_StartTime,
        DetailsReport_Label_EndTime,
        DetailsReport_Label_TimeActive,
        DetailsReport_Label_KmGPS,
        DetailsReport_Label_KmCO,
        DetailsReport_Label_QuotaFuel,
        DetailsReport_Label_QuotaFuelConsume,
        DetailsReport_Label_StartAddress,
        DetailsReport_Label_EndAddress,
        DetailsReport_Label_TripCompensatory,

        DetailsReport_Table_Serial,
        DetailsReport_Table_CurrentTime,
        DetailsReport_Table_StartEndTime,
        DetailsReport_Table_TimeActive,
        DetailsReport_Table_KmGPS,
        DetailsReport_Table_KmCO,
        DetailsReport_Table_VehicleType,
        DetailsReport_Table_VehiclePlate,
        DetailsReport_Table_QuotaFuel,
        DetailsReport_Table_QuotaFuelConsume,
        DetailsReport_Table_StartAddress,
        DetailsReport_Table_EndAddress,
        DetailsReport_Table_TripCompensatory,

        DetailsReport_CheckBox_VehicleType,
        DetailsReport_CheckBox_VehiclePlate,
        DetailsReport_CheckBox_TripCompensatory,
        DetailsReport_CheckBox_CurrentTime,
        DetailsReport_CheckBox_TimeActive,
        DetailsReport_CheckBox_KmGPS,
        DetailsReport_CheckBox_QuotaFuel,
        DetailsReport_CheckBox_KmCO,
        DetailsReport_CheckBox_QuotaFuelConsume,
        DetailsReport_CheckBox_StartAddress,
        DetailsReport_CheckBox_EndAddress,

        StopParkingReport_Label_TilePage,
        StopParkingReport_Label_TitlePageDetail,
        StopParkingReport_Label_VehiclePlate,
        StopParkingReport_Label_DriverName,
        StopParkingReport_Label_CodeName,
        StopParkingReport_Label_Phone,
        StopParkingReport_Label_Date,
        StopParkingReport_Label_Time,
        StopParkingReport_Label_StopParkingTime,
        StopParkingReport_Label_MinutesStopRunEngine,
        StopParkingReport_Label_MinutesTurnOnAirConditioner,
        StopParkingReport_Label_StopLocation,
        StopParkingReport_Label_PlaceHolder_NumberOfStopParking,
        StopParkingReport_Label_PlaceHolder_NumberOfStopRunEngine,

        StopParkingReport_Message_ValidateError_StopParkingTime,
        StopParkingReport_Message_ValidateError_MinutesStopRunEngine,

        StopParkingReport_Table_Serial,
        StopParkingReport_Table_DriverName,
        StopParkingReport_Table_CodeName,
        StopParkingReport_Table_Phone,
        StopParkingReport_Table_VehiclePlate,
        StopParkingReport_Table_Date,
        StopParkingReport_Table_Time,
        StopParkingReport_Table_StopParkingTime,
        StopParkingReport_Table_MinutesStopRunEngine,
        StopParkingReport_Table_MinutesTurnOnAirConditioner,
        StopParkingReport_Table_Temperature,
        StopParkingReport_Table_StopLocation,

        StopParkingReport_CheckBox_DriverName,
        StopParkingReport_CheckBox_CodeName,
        StopParkingReport_CheckBox_Phone,
        StopParkingReport_CheckBox_VehiclePlate,
        StopParkingReport_CheckBox_Time,
        StopParkingReport_CheckBox_StopParkingTime,
        StopParkingReport_CheckBox_MinutesStopRunEngine,
        StopParkingReport_CheckBox_MinutesTurnOnAirConditioner,
        StopParkingReport_CheckBox_StopLocation,

        SpeedOversReport_Label_TilePage,
        SpeedOversReport_Label_Group,
        SpeedOversReport_Label_PlaceHolder_Speed,
        SpeedOversReport_Label_TitlePageDetail,
        SpeedOversReport_Label_DetailVehiclePlate,
        SpeedOversReport_Label_Date,
        SpeedOversReport_Label_Time,
        SpeedOversReport_Label_Distance,
        SpeedOversReport_Label_Vmax,
        SpeedOversReport_Label_StartAddress,
        SpeedOversReport_Label_EndAddress,
        SpeedOversReport_Label_Note,

        SpeedOversReport_Message_ValidateError_Speed,

        SpeedOversReport_CheckBox_TotalTime,
        SpeedOversReport_CheckBox_TotalDistance,
        SpeedOversReport_CheckBox_Vmax,
        SpeedOversReport_CheckBox_StartAddress,
        SpeedOversReport_CheckBox_EndAddress,
        SpeedOversReport_CheckBox_Note,

        SpeedOversReport_Table_Serial,
        SpeedOversReport_Table_DetailVehiclePlate,
        SpeedOversReport_Table_Date,
        SpeedOversReport_Table_Time,
        SpeedOversReport_Table_Distance,
        SpeedOversReport_Table_Vmax,
        SpeedOversReport_Table_StartAddress,
        SpeedOversReport_Table_EndAddress,
        SpeedOversReport_Table_Note,

        ReportSignalLoss_Label_TitlePage,
        ReportSignalLoss_Label_TitlePageDetail,
        ReportSignalLoss_TitleStatus,
        ReportSignalLoss_Title_MinTimeLosing,
        ReportSignalLoss_Title_StartTime,
        ReportSignalLoss_Title_EndTime,
        ReportSignalLoss_Title_TimeLosing,
        ReportSignalLoss_Title_StartAddress,
        ReportSignalLoss_Title_EndAddress,
        ReportSignalLoss_TitleStatus_All,
        ReportSignalLoss_TitleStatus_GPS,
        ReportSignalLoss_TitleStatus_GMS,
        ReportSignalLoss_Message_ValidateError_MinTimeLosing,
        ReportSignalLoss_Message_ValidateError_MinTimeLosing2,
        #endregion report

        #region
        ReportTemperature_Label_Temperature,
        ReportTemperature_Label_TitlePage,
        ReportTemperature_Label_Grid_Kilomet,
        ReportTemperature_Label_Grid_DateTime,
        ReportTemperature_Label_Grid_Temperature,
        ReportTemperature_Label_Grid_NumberOfSensors,
        ReportTemperature_Label_Grid_StartAddress,
        ReportTemperature_Label_Grid_EndAddress,
        ReportTemperature_Label_Grid_Description,
        ReportTemperature_Label_Grid_Router,
        ReportTemperature_Message_ValidateError_Temperation,
        ReportTemperature_Label_DetailVehiclePlate,
        ReportTemperature_Label_DetailFromDate,
        ReportTemperature_Label_DetailKM,
        ReportTemperature_Label_DetailTemperature,
        ReportTemperature_Label_DetailStartAddress,
        ReportTemperature_Label_DetailEndAddress,
        ReportTemperature_Label_DetailDescription,
        ReportTemperature_Combobox_LabelAll_StatusMachine,
        ReportTemperature_Label_TitlePageDetail,
        ReportMachine_TitleStatusMachine,
        ReportMachine_Label_PlaceHolder_CountMinutes,
        ReportMachine_Label_PlaceHolder_StatusMachine,
        ReportMachine_Label_Grid_Minutes,
        ReportMachine_Label_TitlePage,
        ReportMachine_Label_Grid_DateTimeEnd,

        ReportMachine_Label_Grid_Fuel,
        ReportMachine_Label_Grid_StartAddress,
        ReportMachine_Label_Grid_EndAddress,
        ReportMachine_Label_DetailVehiclePlate,
        ReportMachine_Label_DetailFromDate,
        ReportMachine_Label_DetailMinutes,
        ReportMachine_Label_DetailFuel,
        ReportMachine_Label_DetailStartAddress,
        ReportMachine_Label_DetailEndAddress,
        ReportMachine_Message_ValidateError_Minutes,
        ReportMachine_Label_Grid_DateTime,
        ReportMachine_Label_TitlePageDetail,
        ReportMachine_Label_EngineTurnOn,
        ReportMachine_Label_EngineTurnOff,

        #endregion

        #region Camera
        Camera_Label_MenuTitle,
        Camera_Label_TitlePage,
        Camera_Label_Video,
        Camera_Label_Chanel,
        CameraImage_Label_TitlelPage,
        CameraImage_Label_TitleDetailPage,
        Common_Message_ErrorTimeFromToTimeEnd,
        Camera_Label_Undefined,
        Camera_Label_Connection_Error,
        Camera_Label_Timeout_Error,
        Camera_Title_Camera_Streaming,
        Camera_Title_Retreaming,
        Camera_Label_Time_Has_Video,
        Camera_Label_Time_Has_VideoSaved,
        Camera_Label_Vehicle_Numbers,
        Camera_Label_Vehicle_Have_Video_Numbers,
        Camera_Label_Video_Numbers,
        Camera_Label_Video_Event_Numbers,
        Camera_Label_Start_Watch,
        Camera_ChildTab_Device,
        Camera_ChildTab_BACloud,
        Camera_Lable_ListVideo,
        Camera_ChildTab_MyVideo,
        Camera_Alert_Title,
        Camera_Alert_HelpContent,
        Camera_Checkbox_AutoRenewal,
        Camera_Lable_Channel,
        Camera_Lable_AllChannel,
        Camera_Lable_Chart,
        Camera_Lable_TimeHasVideo,
        Camera_Lable_TimeSaveVideo,
        Camera_Lable_NoteChart,
        Camera_Title_UploadVideoToServer,
        Camera_Title_NoteDowLoadFile,
        Camera_Lable_NoteUploadVideoToServer,
        UploadVideoTo_Alert_NoteUploaded,
        Camera_Title_Downloadedvideo,
        Camera_Title_Downloadingvideo,
        Camera_Title_ListDownloadingvideo,
        Camera_Status_ErrorConnect,
        Camera_Status_Downloaded,
        Camera_Status_WaitingUpload,
        Camera_Status_Downloading,
        Camera_Status_DownloadError,
        Camera_Lable_ExportVideo,
        Camera_Alert_DownloadedVideo,
        Camera_Lable_CameraDisconnect,
        Camera_Message_StopStreamingOK,
        Camera_Message_StopStreaming,
        Camera_Message_StopPlayback,
        Camera_Message_DeviceStreamingError,
        Camera_Message_DeviceStreamingErrorDetail,
        Camera_Message_PleaseLoadVideo,
        Camera_Message_DowloadVideoSuccess,
        Camera_Message_VideoSaveToServer,
        Camera_Message_DoYouWantDowloadVideo,
        Camera_Message_ChannelNotWorking,
        Camera_Lable_PlaybackDisconnect,
        Camera_Message_StopPlaybackOK,
        Camera_Message_DevicePlaybackErrorDetail,
        Camera_Message_SaveImageSuccess,
        Camera_Message_SaveImageError,
        #endregion

        #region Image
        Image_Lable_Image,
        Image_Lable_ImageMonitoring,
        Image_Lable_Nearestvehicle,
        Image_Alert_SaveImageSuccess,
        Image_Lable_Totalnumberimages,
        #endregion

        #region Helper
        Helper_Label_TitlePage,
        Helper_Label_HeplperVihcleDebt,
        Helper_Label_Using,
        Helper_Label_Using2,
        Helper_Label_HeplperRouter,
        Helper_Label_HeplperListVhicle,
        Helper_Label_HeplperCamera,
        Helper_Label_HeplperlistVihicle,
        Helper_Label_HeplperOnline,
        #endregion

        #region Settings
        Settings_Label_Title,
        Settings_Label_Enable_Cluster,
        Settings_Label_Show_Notification,
        Settings_Label_UseGPSDefault,
        Settings_Label_SettingGenaral,
        Settings_Label_SettingAdvanced,
        Settings_Label_SettingMylocationMap,
        Settings_Label_SettingMylocationMap2,
        Settings_Label_SettingThelocation,
        Settings_Label_SettingReceiveAlert,
        Settings_Label_ListAlert,
        Settings_Label_ListVehicleAlert,
        Settings_Label_ChangeTheme,
        Settings_CheckBox_Light,
        Settings_Checkbox_Dark,
        Settings_Checkbox_Custom,
        #endregion

        #region VehicleGroupLookUp
        VehicleGroupLookUp_Label_Title,
        VehicleGroupLookUp_Label_NotFound,
        VehicleGroupLookUp_Label_Search,
        VehicleGroupLookUp_Label_Confirm,
        #endregion

        #region Ship
        ShipOnlineDetail_Label_TileInforShipOnline,
        ShipOnlineDetail_Label_VehiclePlate,
        ShipOnlineDetail_Label_Location,
        ShipOnlineDetail_Label_HaiLy,
        ShipOnlineDetail_Label_InfoBoat,
        ShipOnlineDetail_Label_DriverName,
        ShipOnlineDetail_Label_PhoneNumber,
        ShipOnlineDetail_Label_Captain,
        ShipOnlineDetail_Label_CaptainPhoneNumber,
        ShipOnlineDetail_Label_BoatMember,
        ShipOnlineDetail_Label_PortStart,
        ShipOnlineDetail_Label_AtTime,
        #endregion

        #region
        Notification_Label_TilePage,
        Notification_Label_DeleteAllNotice,
        Notification_Label_DeleteAllNoticeAction,
        Notification_Label_DeleteNoticeNotSuccess,
        #endregion

        #region bật tắt từ xa
        SendEngineControl_Label_TilePage,
        SendEngineControl_Label_Search,
        SendEngineControl_Label_On,
        SendEngineControl_Label_Off,
        SendEngineControl_Table_Serial,
        SendEngineControl_Table_VehiclePlate,
        SendEngineControl_Table_CurrentTime,
        SendEngineControl_Table_Action,
        SendEngineControl_Table_Status,
        SendEngineControl_Popup_Label_Password,
        SendEngineControl_Popup_Placeholder_Password,
        SendEngineControl_Button_Password,
        SendEngineControl_Label_Warning,
        SendEngineControl_Button_Warning,
        SendEngineControl_Button_Close,
        SendEngineControl_Popup_HeaderTitle,
        SendEngineControl_Warning_Off,
        SendEngineControl_Warning_On,
        SendEngineControl_Label_State_0,
        SendEngineControl_Label_State_1,
        SendEngineControl_Label_State_2,
        SendEngineControl_Label_State_3,
        SendEngineControl_Label_State_100,
        SendEngineControl_Label_On_Success,
        SendEngineControl_Label_Off_Success,
        SendEngineControl_Validate_PasswordInvalid,
        SendEngineControl_Warning_VehilceNotOnline,
        SendEngineControl_Warning_Label,
        SendEngineControl_Label_Confirm,
        SendEngineControl_Message_TurnOn_Engine,
        SendEngineControl_Message_TurnOff_Engine,
        #endregion

        #region khoảng cách tới các tàu
        Distance_Label_TilePage,
        Distance_Label_Vehicle,
        Distance_Label_Time,
        Distance_Label_Speed,
        Distance_Label_Distance,
        Distance_Label_TitleDistance,
        Distance_Label_LostGPS,
        Distance_Message_NoData,
        #endregion

        #region Moto
        SendConfig_Label_TurnOnOff_Running,
        SendConfig_Label_TurnOnOff_Fail,
        SendConfig_Label_TurnOnOff_Success,
        SendConfig_Label_TurnOnOff_NotOnline,
        SendConfig_Label_TurnOnOff_NotSupport,
        RegisterConfig_Label_PhoneNumber1,
        RegisterConfig_Label_PhoneNumber2,
        RegisterConfig_Label_PhoneNumber3,
        Moto_Label_Setting,
        Moto_Label_Infomation,
        Moto_Label_Status_Device,
        Moto_Label_Alter,
        Moto_Label_Confirm,
        Moto_Message_Alter,
        Moto_Message_Alter_WarningNumber,
        Moto_Message_AllowTurnOnOffEngineViaSMS,
        Moto_Label_Call_Operator,
        Moto_Message_Call_Operator,
        Moto_Message_TurnOn_Engine,
        Moto_Message_TurnOff_Engine,
        Moto_Message_Send_Location,
        Moto_Message_Config_PhoneNumber,
        Moto_Label_Battery_Voltage,
        Moto_Label_Machine_Status,
        Moto_Label_Power_Mode_Used,
        Moto_Label_Time_Connected_To_The_System,
        Moto_Label_Time_To_Update_Location,
        Moto_Label_Disconnection_Time,
        Moto_Label_Configure_SMS_Alerts,
        Moto_Label_Allows_Remote_Engine,
        Moto_Label_Allows_Phone_Calls,
        Moto_Label_Turn_On_Alarm,
        Moto_Label_Turn_On_Alarm_Note,
        Moto_Label_Turn_Off_Alarm,
        Moto_Label_Turn_Off_Alarm_Note,
        Moto_Label_Low_Voltage_Warning,
        Moto_Label_Set_The_Phone,
        Moto_Label_Set_Phone_Number,
        Moto_Label_Speed,
        Moto_Label_Status,
        #endregion

        #region AccountTab
        AccountTab_Label_Notification,
        AccountTab_Label_ChangePassword,
        AccountTab_Label_CustomerSupport,
        AccountTab_Label_DeviceManual,
        AccountTab_Label_BAGPS_Introduce,
        AccountTab_Label_Share,
        AccountTab_Label_Rating,
        AccountTab_Label_Setting,
        AccountTab_Label_Upgrade,
        AccountTab_Label_Logout,
        AccountTab_Label_MessageWarningLogout,
        AccountTab_Label_MyInformation,
        #endregion

        #region Alert Config

        AlertConfig_Label_Alter,
        AlertConfig_Label_SendSuccess,
        AlertConfig_Label_SendFail,
        AlertConfig_Label_Choose_Time,
        AlertConfig_Label_Warning_Alert,
        AlertConfig_Label_Warning_Vehicle,
        AlertConfig_Label_Warning_Time,
        AlertConfig_Label_All_Warnings,
        AlertConfig_Label_All_Warnings_Description,
        AlertConfig_Label_NextStep,
        AlertConfig_Label_All_Vehicle,
        AlertConfig_Label_All_Vehicle_Description,
        AlertConfig_Label_All_Vehicle_Not_Configured,
        AlertConfig_Label_About_Time,
        AlertConfig_Label_Start_Time,
        AlertConfig_Label_End_Time,
        AlertConfig_Label_Choose_Time_Zone,
        AlertConfig_Label_Choose_All_Time_Zone,
        AlertConfig_Label_Save_Configuration,

        #endregion Alert Config

        Boundary_Label_Title,
        Boundary_Label_All,
        Boundary_Label_Showarea,
        Boundary_Label_Showname,

        #region Danh sách lái xe
        ListDriver_Label_Delete,
        ListDriver_Messenger_Delete,
        ListDriver_Messenger_NotNull,
        ListDriver_Messenger_NotSelect,
        ListDriver_Title_Update,
        ListDriver_Title_Insert,
        ListDriver_Title_Success,
        ListDriver_Messenger_LicenseRank,
        ListDriver_Messenger_DuplicateData,
        ListDriver_Messenger_LicenseType,
        ListDriver_Item_SelectLicenseType,
        ListDriver_Messenger_Gender,
        ListDriver_Notify_DateGreater,
        ListDriver_Item_SelectGender,
        ListDriver_Item_Male,
        ListDriver_Item_Female,
        ListDriver_Item_Other,
        ListDriver_Messenger_UpdateSuccess,
        #endregion

        #region PaperInfor
        PaperInfor_Page_Title,
        PaperInfor_Msg_Expired,
        PaperInfor_Msg_NearExpire,


        #endregion
        #region Issue
        Issue_Label_TilePage,
        ListIssue_Label_TilePage,
        ListIssue_Label_DueDate,
        ListIssue_Label_NoProcess,
        DetailIssue_Label_TilePage,
        DetailIssue_Label_SubmitSupportRequest,
        DetailIssue_Label_DueDate,
        DetailIssue_Label_ContentIssue,
        DetailIssue_Label_StepIssue
        #endregion
    }
}